### ISSUE TITLE
Multiple exclude patterns ignored except one.

### ISSUE THREAD

**Issue by jwerre** [duniul/clean-modules#8] opened 2021-08-31 15:37 UTC
If you exclude more that one pattern with the ! (in the glob file) or --exclude flag then only one is effective. For example:

Install mongoose and serverless

```bash
npm install mongoose serverless
```

List files to be excluded
```bash
ls node_modules/@serverless/utils/test

  account.js
  cloudformation-schema.js
  config.js
  download.js
  fixture.zip
  get-notifications-mode.js
  inquirer
  is-in-china.js
  log.js
  process-backend-notification-request.js
  telemetry.js

ls node_modules/mongoose/lib/cursor

  AggregationCursor.js
  ChangeStream.js
  QueryCursor.js
```

Clean modules
```bash
clean-modules --yes --exclude "/@serverless/utils/test/" --exclude "/mongoose/lib/cursor/"
```
Files excluded in mongoose package 😀
```bash
ls node_modules/mongoose/lib/cursor
AggregationCursor.js
ChangeStream.js
QueryCursor.js
```
Files *included* in serverless package 😲
```
ls node_modules/@serverless/utils/test
ls: node_modules/@serverless/utils/test: No such file or directory
```

I'd be happy to hop in and contribute to this but I'm not a Typescripter :(

**Comment by duniul** [comment] 2021-09-04 16:47
Hey @jwerre, and thanks for reporting this! 🙏

The issue isn't that you're using multiple exclude patterns, but that the files you are trying to exclude are included by a directory glob and therefore not individually compared with the excluded globs for performance reasons.

I've added a fix for this in https://github.com/duniul/clean-modules/commit/6d4ecebe33034be2a2997ebb93d8c1cb012f363a which is also included in [v2.0.3](https://github.com/duniul/clean-modules/releases/tag/v2.0.3). It adds a tiny bit of overhead when passing custom exclude globs since it has to make another pass on all included files, but it shouldn't be too bad!

The issue with `ChangeStream.js` being included has also been fixed in 2.0.3, see my response to https://github.com/duniul/clean-modules/issues/6.

Closing this for now, feel free to open it again if you're still having issues!

**Closed by duniul** 2021-09-04 16:47 UTC
